arch: s390x
services:
  - docker
script: docker login quay.io -u $ROBOT_USER -p $ROBOT_TOKEN && docker build -f s390x/Dockerfile --tag quay.io/ibmz/alpine:3.11 && docker push quay.io/ibmz/alpine:3.11
